In [4]:
# .where()
import pandas as pd
bond=pd.read_csv('jamesbond.csv')
bond.set_index("Film",inplace=True)
bond.sort_index(inplace=True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [7]:
# show all values whose actor is Sean Connery and expect values are shown as NaN
mask = bond["Actor"] == "Sean Connery"
bond.where(mask)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [11]:
mask2 = bond["Box Office"] > 100
bond.where(mask & mask2)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4